### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by ebal** [PhotoBackup/server-bottle#1]
It would be easier -especially for packaging- to read configuration parameters from a configuration file and not by asking user for input.

Also it would be a parameter for the tcp port so that the user can choose a free tcp port and not the default of 8080.

Finally it would be great if the application could generate a self signed certificate (by enabling it from the configuration file, opt-in).

Looking forward for your project

**Comment by stephanepechard** [comment]
Packaging is the next topic on my todo list about this project, I'll probably have to think about these questions. For the configuration parameters, I don't put them directly in a file, because passwords are hashed before being written on this file. Therefore, I have to ask it to the user. My idea was to ask it at the end of the installation (through pip ideally).

Sure, I should set the tcp port into the configuration file.

Do you have an example about an application generating a self signed certificate? I don't know much about this part. I know it would be better with such a functionnality, but I don't know how to do it properly.

Thanks a lot for your insights! That's typically the kind of things that helps me.

**Comment by ebal** [comment]
You could do a lot of things,

I am thinking:
a. configuration file for packaging
b. use salt with password before hashing
(that could need a change on the android client too)
c. ssl support (the user adds their certs)
d. Create self signed certs 

I guess the choices are infinite (theoretically).

But first thing, first: Configuration

A better way, could be by using something like this: 

configuration.py 

MEDIA_ROOT="/opt/photobackup"
PASSWORD="dummy"
TCP_PORT="8080"

and do the hashing inside photobackup.py

keep the magic running mate!

PS: I may stretch the "security" options/features but ... that's the world we are living at the moment.

**Comment by stephanepechard** [comment]
Considered done with API v2
